In [1]:
import numpy as np

In [7]:
inputs = [[1, 2, 3, 2.5],
         [2.0, 5.0, -1.0, 2.0], 
         [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

#layer_output = np.dot(weights, inputs) + biases
# print(layer_output)

# we have to do transpose of weights for discarding the shape error
# what we do is --> 1*0.2 + 2*-0.8 + 3*-0.5 + 2.5*1.0 and so on and for that, we have to show weights as 4 cross 3 matrix

layer_output = np.dot(inputs, np.array(weights).T) + biases
print(layer_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [15]:
# now, let us create another layer of NN :- 
inputs = [[1, 2, 3, 2.5],
         [2.0, 5.0, -1.0, 2.0], 
         [-1.5, 2.7, 3.3, -0.8]]

weights1 = [[0.2, 0.8, -0.5, 1.0],
          [0.5, -0.91, 0.26, -0.5],
          [-0.26, -0.27, 0.17, 0.87]]

biases1 = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
          [-0.5, 0.12, -0.33],
          [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

layer1_output = np.dot(inputs, np.array(weights1).T) + biases1
print(layer1_output)

print()

layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2
print(layer2_output)


[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [16]:
# let's make class and use the function:

In [19]:
X = [[1, 2, 3, 2.5],
         [2.0, 5.0, -1.0, 2.0], 
         [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [20]:
layer_1 = Layer_Dense(4, 5)
layer_2 = Layer_Dense(5, 2)

layer_1.forward(X)
print(layer_1.output)
layer_2.forward(layer_1.output)
print(layer_2.output)

[[ 0.90109867 -0.16422701  0.59261761 -0.20015804  0.19207417]
 [ 0.51679129 -1.0998315   0.75652568  0.46216772  0.7974058 ]
 [ 0.0276664   0.00444699  0.56286606 -0.38161016 -0.53497966]]
[[-0.06705399  0.04733101]
 [-0.08179212 -0.01586111]
 [-0.03396045 -0.01950209]]
